### ISSUE TITLE
When is this going to get released?

### ISSUE THREAD

**Issue by shreyasshivakumara** [VincentQQu/NVS-SQA#1]
Hi! Great work and paper. I'm curious to know when the code will be released.

Thank you and good luck! :)

**Comment by VincentQQu** [comment]
Hi Shreyas Shivakumara,

Thank you for your interest and kind words about our work! We appreciate your follow-up. Our latest work, which introduces an end-to-end and more robust QA method that eliminates the need for COLMAP by utilizing self-supervised learning for NSS, is currently under review. We plan to release the code shortly after the review process is complete.

Thanks again for your support, and stay tuned!

Best regards,  
Vincent

**Comment by shreyasshivakumara** [comment]
Great, thank you for your reply.

Good luck!
